version: '3.8'

services:
  poupix:
    build: .
    container_name: poupix_app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://poupix_db:5432/poupix
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - poupix_db

  poupix_db:
    image: postgres:17
    container_name: poupix_db
    restart: always
    environment:
      POSTGRES_DB: poupix
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - poupix_data:/var/lib/postgresql/data

volumes:
  poupix_data:
